project:
  type: website
  output-dir: _site

website:
  title: "Takshashila Institution"
  favicon: images/favicon.ico
  search: true
  navbar:
    background: "#610D3D"
    foreground: "white"
    collapse-below: lg
    logo: "assets/images/main-logo.svg"
    logo-alt: "Takshashila Institution"
    title: false
    right:
      - text: "Policy Research"
        menu:
          - text: "Research Areas"
            href: "pages/research_areas.qmd"
          - text: "Latest Analysis"
            href: "pages/latest_analysis.qmd"
          - text: "Newsletters"
            href: "#"
      - text: "Education"
        menu:
          - text: "Fellowships"
            href: "#"
          - text: "Policy School"
            href: "#"
      - text: "Media"
        menu:
          - text: "Podcasts"
            href: "#"
          - text: "Media Appearances"
            href: "#"
          - text: "In the News"
            href: "#"
          - text: "Blogs"
            href: "#"
      - text: "About"
        menu:
          - text: "Team"
            href: "#"
          - text: "Mission"
            href: "#"
          - text: "Milestones"
            href: "#"
          - text: "Careers"
            href: "#"
          - text: "Donate"
            href: "#"
      - text: Events
        href: "#"

format:
  html:
    theme: 
      - default
      - takshashila.scss
    fontfamily: Roboto
    mainfont: Roboto
    css: takshashila.css
    toc: false
    page-layout: full
    # include-in-header:
    #   text: |
    #     <script src= "../utility/script.js" defer></script>
