project:
  type: website
  output-dir: _site

website:
  title: "Takshashila Institution"
  favicon: images/favicon.ico
  search: true
  navbar:
    background: "#610D3D"
    foreground: "white"
    collapse-below: lg
    logo: "assets/images/logo.png"
    logo-alt: "Takshashila Institution"
    title: false
    right:
      - text: "Takshashila Education"
        href: "#"
      - text: "Engage with Us"
        href: "#"
      - text: "About Us"
        menu:
          - text: "Our Story"
            href: "#"
          - text: "Our Team"
            href: "#"
          - text: "Our Values"
            href: "#"
      - text: "Careers"
        href: "#"
      - text: "Donate"
        href: "#"

format:
  html:
    theme: 
      - default
      - takshashila.scss
    fontfamily: Roboto
    mainfont: Roboto
    css: takshashila.css
    toc: false
    page-layout: full
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">