---
title: Policy for Use of Generative AI
subtitle: Principles for the Use of AI at the Takshashila Institution

format:
  html:
    anchor-sections: false
---

*Version 1.0 25th June 2024*

Takshashila Institution permits the responsible use of AI-based tools for research to augment existing research capacities. This includes the use of AI for searching research leads, synthesising information, aid in reasoning, editing written documents, and visualising outputs. Takshashila Institution recommends the following principles for responsible use of AI tools in research: 

### Authors are accountable for the quality of their research

The author(s) is/are responsible for the content. AI cannot be considered an author, and the author(s) are accountable for the paper’s compliance with academic standards of originality, accuracy, plagiarism and attribution to primary sources.

### Transparency

The author(s) is/are responsible for the content. AI cannot be considered an author, and the author(s) are accountable for the paper’s compliance with academic standards of originality, accuracy, plagiarism and attribution to primary sources.

### Samples of how disclosures can be written

- The essay was copy-edited using ChatGPT.  
- This data/chart was created using tool X. 
- The analysis in this paper was done with the support of chatGPT.

### Attribution

Author(s) will not use AI to write out their analyses - instead, the role of the AI is to improve research productivity by reducing time spent on searching for leads. The author(s) is/are expected to use this information to come to their independent conclusions and write those in their own words. All original sources of information should be correctly cited.

Author(s) will verify all information and sources generated using AI tool(s).

### Audit Trail 

Takshashila Institution recommends it as a best practice to maintain a record of prompts used as part of a project’s research work. This record does not need to be published, but can be used to audit the claims of a document if necessary.
