project:
  type: website
  output-dir: "_site"

website:
  title: Takshashila
  image: assets/images/logo_large.png
  favicon: assets/images/logo.png
  open-graph: true
  site-url: https://takshashila.org.in/
  navbar:
    toggle-position: right
    background: "#610D3D"
    search: false
    logo: images/logo_large.png
    logo-alt: "Takshashila Research"
    title: false
    collapse-below: lg
    logo-href: index.qmd
    right:
      - text: Takshashila Education
        href: pages/education.qmd
      - text: About Us
        href: pages/about-us.qmd
      - text: Careers
        href: pages/careers.qmd
      - text: Engage with Us
        href: pages/donate.qmd
      - text: Donate
        href: pages/donate.qmd

format:
  html:
    theme: [lux]
    css: takshashila.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

editor: visual
