name: Nextcloud Content Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyocclient

      - name: Sync content from Nextcloud
        env:
          NEXTCLOUD_URL: ${{ secrets.NEXTCLOUD_URL }}
          NEXTCLOUD_USERNAME: ${{ secrets.NEXTCLOUD_USERNAME }}
          NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
          NEXTCLOUD_CONTENT_PATH: ${{ secrets.NEXTCLOUD_CONTENT_PATH }}
        run: |
          python .github/scripts/sync_nextcloud.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet content/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update content from Nextcloud'
          title: 'Content Update from Nextcloud'
          body: |
            This PR contains the latest content updates from Nextcloud.
            
            - Automated PR created by GitHub Actions
            - Content synced at: ${{ github.event.repository.updated_at }}
          branch: nextcloud-content-update
          base: main
          labels: content-update, automated-pr